# Generated by Django 5.2.6 on 2026-01-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='Cart',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartproduct',
            old_name='Product',
            new_name='product',
        ),
    ]
